[build]
  command = "cd client && npm run build"
  publish = "client/dist"

[context.production.environment]
  VITE_API_URL = "https://cinevistaa.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
